modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
issueTrackerURL="https://github.com/${repository}/issues"

[[mods]] 
    modId="${mod_id}"
    version="${version}"

    displayName="${mod_name}"
    authors="${mod_author}"
    description=''''''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="kotlinforforge"
    mandatory=true
    versionRange="[4.3.0,)"
    ordering="NONE"
    side="BOTH"
