modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/${repository}/issues"

[[mods]] 
    modId="${mod_id}"
    version="${version}"

    displayName="${mod_name}"
    authors="${mod_author}"
    description=''''''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
