# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
kotlin.code.style=official

# Project
mod_version=0.0.0-dev
maven_group=com.possible-triangle
mod_name=Flight Lib
mod_author=possible_triangle
mod_id=flightlib

# Common
mc_version=1.21.1

# Neoforge
neoforge_version=21.1.213

# Fabric
fabric_api_version=0.116.7+1.21.1
fabric_loader_version=0.17.3

# Dependencies
curios_forge_version=9.2.2
trinkets_version=3.10.0
cca_version=6.3.0
kotlin_fabric_version=1.13.3+kotlin.2.1.21
kotlin_forge_version=5.8.0

# Publishing
repository=pssbletrngle/flightlib