# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
kotlin.code.style=official

# Project
mod_version=4.0.<patch>
maven_group=com.possible-triangle
mod_name=Flight Lib
mod_author=possible_triangle
mod_id=flightlib
mod_description=library for jetpack-like behaviour
version_strategy=suffix_minecraft_version

# Common
mc_version=1.21.1
parchment_mappings_version=2024.11.17

# Neoforge
neoforge_version=21.1.219

# Fabric
fabric_api_version=0.116.9+1.21.1
fabric_loader_version=0.18.4

# Dependencies
kotlin_fabric_version=1.13.3+kotlin.2.1.21
kotlin_forge_version=5.8.0

# Publishing
repository=pssbletrngle/flightlib
