# <meta>
#    <source>@pssbletrngle/github-meta-generator</source>
#    <version>1.0.115</version>
#    <timestamp>2026-07-30T07:46:41.060Z</timestamp>
#    <hash>9d521ee415ea61ee</hash>
# </meta>

blank_issues_enabled: false
